name: PHP Composer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.4'

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Run cs-check
      run: composer cs-check

    - name: Run phpstan
      run: composer phpstan

    - name: Run phpunit
      run: composer test

    - name: Run deptrack modules
      run: composer deptrac-modules

    - name: Run deptrack layers
      run: composer deptrac-layers

